[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

# Async PostgreSQL driver string fallback
sqlalchemy.url = postgresql+asyncpg://neondb_owner:npg_tqEKz0aW6CIb@ep-sweet-dawn-ar4h34lq-pooler.c-4.us-west-2.aws.neon.tech/neondb?sslmode=require
[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S