"""initial_schema_baseline

Revision ID: 8eb0b05a4ef4
Revises: 
Create Date: 2026-09-10 15:17:01.464142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eb0b05a4ef4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_email', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('user_role', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('method', sa.String(length=10), nullable=False))
    op.add_column('audit_logs', sa.Column('endpoint', sa.String(length=255), nullable=False))
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=False))
    op.add_column('audit_logs', sa.Column('client_ip', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('execution_time_ms', sa.Float(), nullable=False))
    op.add_column('audit_logs', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_endpoint'), 'audit_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_audit_logs_method'), 'audit_logs', ['method'], unique=False)
    op.create_index(op.f('ix_audit_logs_status_code'), 'audit_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'action')
    op.drop_constraint(op.f('conversions_customer_id_fkey'), 'conversions', type_='foreignkey')
    op.drop_constraint(op.f('conversions_lead_id_fkey'), 'conversions', type_='foreignkey')
    op.create_foreign_key(None, 'conversions', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversions', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversions', type_='foreignkey')
    op.drop_constraint(None, 'conversions', type_='foreignkey')
    op.create_foreign_key(op.f('conversions_lead_id_fkey'), 'conversions', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key(op.f('conversions_customer_id_fkey'), 'conversions', 'customers', ['customer_id'], ['id'])
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status_code'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_method'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_endpoint'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'meta_data')
    op.drop_column('audit_logs', 'execution_time_ms')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'client_ip')
    op.drop_column('audit_logs', 'status_code')
    op.drop_column('audit_logs', 'endpoint')
    op.drop_column('audit_logs', 'method')
    op.drop_column('audit_logs', 'user_role')
    op.drop_column('audit_logs', 'user_email')
    # ### end Alembic commands ###